[package]
name = "server"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]
edition = "2018"
rust-version = "1.56"

[dependencies]
tokio = { version = "1.0", features = [ "full" ] }
argh = "0.1"
async-nats-tokio-rustls-deps = { path = "../.." }
rustls-pemfile = "1.0"
